const String css_style = "<style>"
                         "body {"
                         "background-color: #dce3e3;"
                         "text-align: center;"
                         "font-family: Arial, Helvetica, sans-serif;"
                         "font-size: 18px;"
                         "}"
                         "input[type=button], input[type=submit], input[type=reset] {"
                         "background-color: #4CAF50;"
                         "border: none;"
                         "color: white;"
                         "padding: 16px 32px;"
                         "text-decoration: none;"
                         "margin: 4px 2px;"
                         "cursor: pointer;"
                         "}"
                         "input[type=text], input[type=password] {"
                         " width: 50%;"
                         "padding: 12px 20px;"
                         "margin: 8px 0;"
                         "box-sizing: border-box;"
                         "background-color: #FFFFFF;"
                         "}"
                         "h1 {"
                         "color: white;"
                         "text-align: center;"
                         "font-family: Arial, Helvetica, sans-serif;"
                         "font-size: 24px;"
                         "letter-spacing: 2px;"
                         "word-spacing: 2px;"
                         "color: #494949;"
                         "font-weight: normal;"
                         "text-decoration: none;"
                         "font-style: normal;"
                         "font-variant: small-caps;"
                         "text-transform: none;"
                         "}"
                         "h4 {"
                         "font-family: Arial, Helvetica, sans-serif;"
                         "font-size: 18px;"
                         "color: #494949;"
                         "font-weight: normal;"
                         "text-decoration: none;"
                         "font-style: normal;"
                         "font-variant: normal;"
                         "text-transform: none;"
                         "}"
                         "p {"
                         " font-family: verdana;"
                         "font-size: 20px;"
                         "}"
                         ".grid-container {"
                         "justify-content: space-evenly;"
                         "justify-items: center;"
                         "display: grid;"
                         "grid-template-columns: auto auto auto;"
                         "background-color: rgba(201, 240, 240, 0.8);"
                         "}"
                         ".grid-item {"
                         "border: 3px solid rgba(0, 0, 0, 0.2);"
                         "padding: 2px;"
                         "font-size: 18px;"
                         "text-align: center;"
                         "}"
                         "</style>";
